### ISSUE TITLE
Native 4-byte addressing

### ISSUE THREAD

**Issue by eswierk** [dword1511/stm32-vserprog#12]
It would be nice to support larger-capacity SPI NOR flash chips like W25256FV and N25Q256A that require 4-byte addressing.

**Comment by dword1511** [comment]
`flashrom` currently does not support 4-byte addressing as far as I known. There were [patches](https://mail.coreboot.org/pipermail/flashrom/2015-January/013168.html) proposed but they are probably unmerged.

**Comment by eswierk** [comment]
I've managed to get a flashrom with those patches working well enough to program an N25Q256A using an FT232H module, but it's awfully slow.

https://github.com/skyportsystems/flashrom/commits/master

**Comment by eswierk** [comment]
It is possible to program N25Q/MT25QL chips larger than 16 MB with the existing flashrom serprog, using only commands with 3-byte addresses, plus the extended address register for the 4th byte. See https://github.com/skyportsystems/flashrom/commit/60b1084b for an example.

Other chips may require native 4-byte addressing, but I haven't encountered them so far.

**Comment by dword1511** [comment]
With a proper patch for `flashrom`, any serprog should be able to handle 4-byte addressing. It is merely an SPI-to-USB bridge. It has no knowledge about the protocol. The commands with address parameters in serprog protocol are for parallel flash chips. The only limitation for serprog with SPI is that the size of each transaction (command or data) must be under 16MB.

**Comment by eswierk** [comment]
Ah! Thanks for the clarification. I confirmed that programming an M25QL256 with flashrom serprog works with direct 4-byte address commands. See https://github.com/skyportsystems/flashrom/commit/d30fcd40 .
