### ISSUE TITLE
~~x�~hellowor problem

### ISSUE THREAD

**Issue by atesonur** [dword1511/stm32-vserprog#15]
Thank you so much for your code, it helped me a lot. But I have a problem. When I start up my stm32f103 device and try to read 14 bytes from virtual port by using usb_getc(),  First 6 bytes are  always like ~~x�~ these. I understood that they stay there when I start up system and if I write 14 bytes,  I can only write first 8 bytes The first 6 bytes already occupied by these characters.
Do you have any suggestion and thanks a lot for the code you support.

**Comment by dword1511** [comment]
Check whether there are other programs accessing the serial port.

**Comment by atesonur** [comment]
Thank you so much for your time. None of my programs are using serial port and even I restarted my computer just in case. I am using linux and after restart,  I got these:

master@Lenovo:~/Desktop$ sudo python echo2.py helloworldonur
~~x�~hellowor
master@Lenovo:~/Desktop$ sudo python echo2.py helloworldonur
ldonurhellowor

Thank you so much.

**Comment by dword1511** [comment]
I do not know what you are using. Can you use `minicom`?

Make sure `ModemManager` is not running.

**Comment by atesonur** [comment]
Thank you so much. I used minicom. It is same but i used a similar command handler like you do. It works fine. Thanks a lot for your time.

**Comment by dword1511** [comment]
Without the exact description of your code and what you are doing, I cannot help you. If it is a project of your own, please use email rather than issues. Thanks!
