### ISSUE TITLE
驱动这块会不会有问题？

### ISSUE THREAD

**Issue by Droid-MAX** [dword1511/stm32-vserprog#19]
从打板到元器件采购到组装焊接再到编译烧录程序这整个流程都没有问题，但在Windows10/Linux系统的主机上使用时却无法正常识别出来，指示灯正常工作
PS：第一次插上去时在设备管理器中有个未知设备一闪而过，之后一点反应都没有
不知道是不是因为当时误把22千欧(片上标识为223)的贴片电阻用在R2和R4的缘故，不过现在已经换回来了
除此之外该排查的地方也都排查过了，仍未确定问题所在。。。

**Comment by dword1511** [comment]
USB 1.5K 的上拉没有问题吗？Linux 下的 dmesg 看一下？确认 STM32 是原装正片？

**Comment by Droid-MAX** [comment]
电阻片上标识为152，也测量过了，是1.5千欧没错
编译好的固件可以顺利烧录进去(烧录是在windoows平台下用flymcu搞定的，还没用到stm32flash)，但就是识别不了，非常郁闷。。

**Comment by Droid-MAX** [comment]
问题已解决，原因在于按照README的操作步骤编译得来的是V2版本的固件，烧录到V3版本的板子里去的话是绝对有问题的，今天心血来潮又重新捡起了板子，修改了编译参数得到了V3版本固件，重新烧录到编程器当中，最终如愿以偿，非常感谢大佬的这个非常优秀的项目！
