### ISSUE TITLE
Cosmic/18.04: Had to install libnewlib-arm-none-eabi to resolve stdint.h not found error.

### ISSUE THREAD

**Issue by kamilion** [dword1511/stm32-vserprog#27]
Went and got stm32flash and gcc-arm-none-eabi on cosmic, but build failed. Googling indicated the package 'libnewlib-arm-none-eabi' was missing. Installed it. Build successful.

**Comment by dword1511** [comment]
Thanks for the feedback. On most of the systems `gcc-arm-none-eabi` should depend on `newlib`. I will add a heads-up in the README.
