### ISSUE TITLE
How to use udev rules to make a symbol link of /dev/ttyACM<N>

### ISSUE THREAD

**Issue by KalelCooper** [dword1511/stm32-vserprog#28]
First  let's see how 'Black Magic Probe' did this:
```
$ udevadm info --attribute-walk /dev/ttyACM0
  looking at device '/devices/pci0000:00/0000:00:1a.1/usb4/4-1/4-1:1.0/tty/ttyACM0':
    KERNEL=="ttyACM0"
    SUBSYSTEM=="tty"
    DRIVER==""

  looking at parent device '/devices/pci0000:00/0000:00:1a.1/usb4/4-1/4-1:1.0':
    KERNELS=="4-1:1.0"
    SUBSYSTEMS=="usb"
    DRIVERS=="cdc_acm"
    ...
    ATTRS{interface}=="Black Magic GDB Server"
```
And it's udev rules like this:
```
DRIVERS=="cdc_acm", ATTRS{interface}=="Black Magic GDB Server", SYMLINK+="bmp_gdb"
DRIVERS=="cdc_acm", ATTRS{interface}=="Black Magic UART Port", SYMLINK+="bmp_uart"
```

But stm32-vserprog has no such thing like ATTRS{interface} :
```
$ udevadm info --attribute-walk /dev/ttyACM2
  looking at device '/devices/pci0000:00/0000:00:1d.2/usb8/8-2/8-2:1.0/tty/ttyACM2':
    KERNEL=="ttyACM2"
    SUBSYSTEM=="tty"
    DRIVER==""
  looking at parent device '/devices/pci0000:00/0000:00:1d.2/usb8/8-2/8-2:1.0':
    KERNELS=="8-2:1.0"
    SUBSYSTEMS=="usb"
    DRIVERS=="cdc_acm"
    ...
    ATTRS{supports_autosuspend}=="1"
```
So, how to add "ATTRS{interface}" to stm32-vserprog ?

**Comment by dword1511** [comment]
Use `ATTR{ID_MODEL}=="STM32_virtual_serprog_for_flashrom"`. I did not specify strings for individual interfaces.

**Comment by KalelCooper** [comment]
> Use `ATTR{ID_MODEL}=="STM32_virtual_serprog_for_flashrom"`. I did not specify strings for individual interfaces.

I'm using eudev, not systemd. 
Udev can only got remove action event with  `ENV{ID_MODEL}=="STM32_virtual_serprog_for_flashrom"`.

After some investigation I give up to make it make symbol link.
I thought add  ATTRS{interface} string maybe a easier way. I tried to add one more string to char *usb_strings[] in usbcdc.c and modify usbd_init(..., 4, ...) . But still not work.

And finally, I use below code to get the real device.
`$(realpath /dev/serial/by-id/*STM32_virtual_serprog_for_flashrom*)`
