### ISSUE TITLE
Write HAL to handle different MCU

### ISSUE THREAD

**Issue by dword1511** [dword1511/stm32-vserprog#3]
Currently there is a lot of macros everywhere. Need to abstract things up and put them together.

**Comment by Kurnihil** [comment]
After this rewriting it would be possible to use your library (program?) with the NXP board "FRDM-KE06Z" (MKE06Z128VLK4 MCU)..?

**Comment by dword1511** [comment]
I do not have the board, and it seems libopencm3 currently does not support this MCU, so I think it will not.
