### ISSUE TITLE
关于针对W25Q256FV的4Byte地址模式的支持

### ISSUE THREAD

**Issue by Droid-MAX** [dword1511/stm32-vserprog#50]
...

**Comment by Droid-MAX** [comment]
https://github.com/dword1511/stm32-vserprog/issues/12 

看来还是得从上位机入手

**Comment by dword1511** [comment]
QSPI 跟 4-byte address 是两回事。4-byte address 用于支持 32M 和更大的闪存。

QSPI 有四根数据线。大部分 STM32 不支持这种接口。新一点的 F4 有支持。不过意义不大，因为 USB 2.0 FS 跑不了那么快，除非加上 HS PHY 。

**Comment by Droid-MAX** [comment]
那如果想解决4-byte地址模式这个问题的话是不是还是得从上位机入手？比如修改flashrom的源码？

**Comment by dword1511** [comment]
最新的 flashrom 应该已经支持 4BA 了
https://www.flashrom.org/Flashrom/1.1

**Comment by Droid-MAX** [comment]
我知道问题所在了！
对于Winbond W25Q256FV闪存芯片来说，flashrom确实已经支持4Byte地址模式操作，不过决定闪存工作在3Byte/4Byte地址模式的ADP寄存器状态并未被设置为4Byte地址模式，所以导致系统无法正常启动的问题。同时我也找到了一个针对W25Q256FV的ADP寄存器状态设置的修改版flashrom，已通过测试。
https://github.com/huming2207/flashrom_google
我也给编译到了Windows平台上
https://github.com/Droid-MAX/flashrom_mod/releases/tag/1.0

**Comment by Droid-MAX** [comment]
已结案，故close该issue.
