### ISSUE TITLE
flashrom Git URL needs updating

### ISSUE THREAD

**Issue by onetransistor** [dword1511/stm32-vserprog#51]
I tried to pull and compile this repo and it fails because of flashrom. The [Git URL of flashrom submodule](https://github.com/dword1511/stm32-vserprog/blob/master/.gitmodules) should be updated from:

```
[submodule "flashrom"]
	path = flashrom
	url = https://www.flashrom.org/git/flashrom.git
	branch = staging
```

to:

```
[submodule "flashrom"]
	path = flashrom
	url = https://github.com/flashrom/flashrom.git
	branch = master
``` 

It would then compile without errors.

**Comment by dword1511** [comment]
Fixed by #52
